INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('AF', 'AFG', 004, 'Afghanistan ', 'Afganistan');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('AX', 'ALA', 248.0, 'Ålland Islands ', 'Alandski otoki', 'Otočje v Baltiku.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('AL', 'ALB', 008, 'Albania ', 'Albanija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('DZ', 'DZA', 012, 'Algeria ', 'Alžirija', 'Koda po kabilskem nazivu: Dzayer.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('AS', 'ASM', 016, 'American Samoa ', 'Ameriška Samoa', 'Zunanji teritorij ZDA v južnem Tihem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('AD', 'AND', 020, 'Andorra ', 'Andora');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('AO', 'AGO', 024, 'Angola ', 'Angola');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('AI', 'AIA', 660.0, 'Anguilla ', 'Angvila', 'Čezmorska skupnost Velike Britanije, predhodno je AI predstavljal francoski: Afar and Issas.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('AQ', 'ATA', 010, 'Antarctica ', 'Antarktika', 'Koda pa francoskem nazivu: Antarctique.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('AG', 'ATG', 028, 'Antigua and Barbuda ', 'Antigva in Barbuda', 'Otoška država v malih Antilih v Karibskem morju.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('AR', 'ARG', 032, 'Argentina', 'Argenitna');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('AM', 'ARM', 051, 'Armenia ', 'Armenija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('AW', 'ABW', 533, 'Aruba ', 'Aruba', 'Otok v Karibskem morju, del kraljevine Nizozemske.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('AU', 'AUS', 036, 'Australia ', 'Avstralija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('AT', 'AUT', 040, 'Austria ', 'Avstrija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('AZ', 'AZE', 031, 'Azerbaijan ', 'Azerbajdžan');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BS', 'BHS', 044, 'Bahamas ', 'Bahami');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BH', 'BHR', 048, 'Bahrain ', 'Bahrajn');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BD', 'BGD', 050, 'Bangladesh ', 'Bangladeš');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BB', 'BRB', 052, 'Barbados ', 'Barbados');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('BY', 'BLR', 112, 'Belarus ', 'Belorusija', 'Bivši ISO naziv države: Byelorussian SSR.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BE', 'BEL', 056, 'Belgium ', 'Belgija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BZ', 'BLZ', 084, 'Belize ', 'Belize');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('BJ', 'BEN', 204, 'Benin ', 'Benin', 'Bivši ISO naziv države: Dahomey (DY).');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BM', 'BMU', 060, 'Bermuda ', 'Bermudi');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BT', 'BTN', 064, 'Bhutan ', 'Butan');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BO', 'BOL', 068, 'Bolivia, Plurinational State of ', 'Bolivija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('BQ', 'BES', 535, 'Bonaire, Sint Eustatius and Saba ', 'Otočje Bonaire, Sv. Eustatij in Saba', 'Otočje v karibih pod nizozemsko upravo (the BES Islands). Bivši ISO naziv države: Bonaire, Saint Eustatius and Saba. BQ je prej predstavljal: British Antarctic Territory.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BA', 'BIH', 070, 'Bosnia and Herzegovina ', 'Bosna in Hercegovina');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BW', 'BWA', 072, 'Botswana ', 'Bocvana');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('BV', 'BVT', 074, 'Bouvet Island ', 'Bouvetov otok', 'Norveški otok v južnem Atlantskem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BR', 'BRA', 076, 'Brazil ', 'Brazilija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('IO', 'IOT', 086, 'British Indian Ocean Territory ', 'Britansko ozemlje v Indijskem oceanu');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('BN ', 'BRN', 096, 'Brunei Darussalam ', 'Brunej', 'ISO naziv države po nazivu v ZN. Otoška država na otok Borneo v JV Aziji.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BG', 'BGR', 100, 'Bulgaria ', 'Bolgarija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('BF ', 'BFA', 854, 'Burkina Faso ', 'Burkina Faso', 'Bivši ISO naziv države: Upper Volta (HV).');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('BI', 'BDI', 108, 'Burundi ', 'Burundi ');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('KH', 'KHM', 116, 'Cambodia ', 'Kambodža', 'Koda po bivšem nazivu: Khmer Republic. Bivši ISO naziv države: Kampuchea.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('CM', 'CMR', 120, 'Cameroon ', 'Kamerun');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('CA', 'CAN', 124, 'Canada ', 'Kanada');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('CV', 'CPV', 132, 'Cape Verde ', 'Kapverdski otoki (Zelenortski otoki)', 'Otočje v Atlantskem oceanu ob Afriki.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('KY', 'CYM', 136, 'Cayman Islands ', 'Kajmanski otoki');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('CF', 'CAF', 140, 'Central African Republic ', 'Srednjeafriška republika', 'Prej znana kot francoska kolonija Ubangi-Shari.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('TD', 'TCD', 148, 'Chad ', 'Čad', 'Koda po francoskem nazivu: Tchad.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('CL', 'CHL', 152, 'Chile ', 'Čile');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('CN', 'CHN', 156, 'China ', 'Kitajska');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('CX', 'CXR', 162, 'Christmas Island ', 'Božični otok', 'Avstralsko ozemlje v Indijskem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('CC', 'CCK', 166, 'Cocos (Keeling) Islands ', 'Kokosovi in Keelingovi otoki', 'Otočje pod upravo Avstralije v Indijskem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('CO', 'COL', 170, 'Colombia ', 'Kolumbija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('KM ', 'COM', '174', 'Comoros ', 'Komori', 'Otočje v Indijskem oceanu. Koda po nazivu v komorščini: Komori.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('CG', 'COG', 178, 'Congo ', 'Kongo', 'Srednji Kongo (celinska država brez morja).');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('CD', 'COD', 180, 'Congo, the Democratic Republic of the ', 'Demokratična republika Kongo', 'Bivše ime: Zaire (ZR), obmorska država.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('CK', 'COK', 184, 'Cook Islands ', 'Cookovi otoki');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('CR', 'CRI', 188, 'Costa Rica ', 'Kostarika');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('CI', 'CIV', 384, 'Côte d\'Ivoire', 'Slonokoščena obala');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('HR', 'HRV', 191, 'Croatia ', 'Hrvaška', 'Koda po nazivu v hrvaščini: Hrvatska.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('CU', 'CUB', 192, 'Cuba ', 'Kuba');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('CW', 'CUW', 531, 'Curaçao ', 'Kurasao', 'Spada v čezmorsko ozemlje Nizozemske, Nizozemski Antili.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('CY', 'CYP', 196, 'Cyprus ', 'Ciper');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('CZ', 'CZE', 203, 'Czech Republic ', 'Češka');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('DK', 'DNK', 208, 'Denmark ', 'Danska');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('DJ', 'DJI', 262, 'Djibouti ', 'Džibuti', 'Staro ime: French Afar and Issas (AI).');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('DM', 'DMA', 212, 'Dominica ', 'Dominika', 'Otoška država v malih Antilih v Karibskem morju.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('DO', 'DOM', 214, 'Dominican Republic ', 'Dominikanska republika');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('EC', 'ECU', 218, 'Ecuador ', 'Ekvador');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('EG', 'EGY', 818, 'Egypt ', 'Egipt');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SV', 'SLV', 222, 'El Salvador ', 'Salvador');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('GQ', 'GNQ', 226, 'Equatorial Guinea ', 'Ekvatorialna Gvineja', 'Koda po francoskem nazivu: Guinée équatoriale.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('ER', 'ERI', 232, 'Eritrea ', 'Eritreja');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('EE', 'EST', 233, 'Estonia ', 'Estonija', 'Koda po estonskem nazivu: Eesti.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('ET', 'ETH', 231, 'Ethiopia ', 'Etiopija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('FK', 'FRO', 234, 'Falkland Islands (Malvinas) ', 'Falkalndski otoki', 'Čezmorsko otočje velike Britanije.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('FO', 'FLK', 238, 'Faroe Islands ', 'Ferski otoki');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('FJ', 'FJI', 242, 'Fiji ', 'Fidži', 'Otočje v južnem Tihem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('FI', 'FIN', 246, 'Finland ', 'Finska');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('FR', 'FRA', 250, 'France ', 'Francija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('GF', 'GUF', 254, 'French Guiana ', 'Francoska Gvajana', 'Koda po francoskem nazivu: Guyane française.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('PF', 'PYF', 258, 'French Polynesia ', 'Francoska Polinezija', 'Čezmorsko otočje Francije v južnem Tihem oceanu. Koda po francoskem nazivu: Polynésie française.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('TF', 'ATF', 260, 'French Southern Territories ', 'Francoska južna ozemlja', 'Predstavlja francoske vulkanske otoke JV od Afrike v Indijskem oceanu in del antarktike, ki Franciji niso mednarodno priznani. Koda po francokem nazivu: Terres australes françaises.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('GA', 'GAB', 266, 'Gabon ', 'Gabon');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('GM', 'GMB', 270, 'Gambia ', 'Gambija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('GE', 'GEO', 268, 'Georgia ', 'Gruzija', 'Koda GE je prej predstavljala Gilbertove in Ellisijine otoke.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('DE', 'DEU', 276, 'Germany ', 'Nemčija', 'Koda po nemškem nazivu: Deutschland. Koda pred 1990 v uporabi za Zahodno Nemčijo.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('GH', 'GHA', 288, 'Ghana ', 'Gana');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('GI', 'GIB', 292, 'Gibraltar ', 'Gibraltar');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('GR', 'GRC', 300, 'Greece ', 'Grčija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('GL', 'GRL', 304, 'Greenland ', 'Grenlandija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('GD', 'GRD', 308, 'Grenada ', 'Grenada');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('GP', 'GLP', 312, 'Guadeloupe ', 'Guadeloupe', 'Čezmorski otok Francije v Karibskem morju.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('GU', 'GUM', 316, 'Guam ', 'Guam', 'Zunanji teritorij ZDA v Tihem oceanu (tudi Guahan).');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('GT', 'GTM', 320, 'Guatemala ', 'Gvatemala');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('GG', 'GGY', 831, 'Guernsey ', 'Otok Guernsey', 'Bailwick of Goursey je Britanski otok ob Franciji.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('GN', 'GIN', 324, 'Guinea ', 'Gvineja');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('GW', 'GNB', 624, 'Guinea-Bissau ', 'Gvineja-Bissau');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('GY', 'GUY', 328, 'Guyana ', 'Gvajana');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('HT', 'HTI', 332, 'Haiti ', 'Haiti');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('HM', 'HMD', 334, 'Heard Island and McDonald Islands ', 'Otok Heard in otočje McDonald', 'Nenaseljeno otočje v Indijskem oceanu pod upravo Avstralije.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('VA', 'VAT', 336, 'Holy See (Vatican City State) ', 'Vatikan', 'Bivši ISO naziv države: Vatican City State (Vatikanska mestna država).');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('HN', 'HND', 340, 'Honduras ', 'Honduras');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('HK', 'HKG', 344, 'Hong Kong ', 'Hong Kong');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('HU', 'HUN', 348, 'Hungary ', 'Madžarska');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('IS', 'ISL', 352, 'Iceland ', 'Islandija', 'Koda po nazivu v islandščini: Ísland.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('IN', 'IND', 356, 'India ', 'Indija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('ID', 'IDN', 360, 'Indonesia ', 'Indonezija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('IR', 'IRN', 364, 'Iran, Islamic Republic of ', 'Iran');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('IQ', 'IRQ', 368, 'Iraq ', 'Irak');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('IE', 'IRL', 372, 'Ireland ', 'Irska');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('IM', 'IMN', 833, 'Isle of Man ', 'Otok Man', 'Spada neposredno pod Britansko krono a ni del Velike Britanije, nahaja se med Irsko in Veliko Britanijo.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('IL', 'ISR', 376, 'Israel ', 'Izrael');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('IT', 'ITA', 380, 'Italy ', 'Italija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('JM', 'JAM', 388, 'Jamaica ', 'Jamajka');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('JP', 'JPN', 392, 'Japan ', 'Japonska');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('JE', 'JEY', 832, 'Jersey ', 'Otok Jersey', 'Bailwick of Jersey je Britanski otok med Anglijo in Francijo.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('JO', 'JOR', 400, 'Jordan ', 'Jordanija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('KZ', 'KAZ', 398, 'Kazakhstan ', 'Kazahstan', 'Bivši ISO naziv države: Kazakstan.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('KE', 'KEN', 404, 'Kenya ', 'Kenija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('KI', 'KIR', 296, 'Kiribati ', 'Kiribati', 'Razpršeno otočje v Tihem oceanu. Stari naziv: Gilbertovi otoki.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('KP', 'PRK', 408, 'Korea, Democratic People\'s Republic of ', 'Severna Koreja', 'ISO naziv države po uradnem nazivu v ZN (splošno ime: Severna Koreja).');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('KR', 'KOR', 410, 'Korea, Republic of ', 'Južna Koreja', 'ISO naziv države po uradnem nazivu v ZN (splošno ime: Južna Koreja).');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('KW', 'KWT', 414, 'Kuwait ', 'Kuvajt');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('KG', 'KGZ', 417, 'Kyrgyzstan ', 'Kirgizistan (Kirgizija)');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('LA', 'LAO', 418, 'Lao People\'s Democratic Republic ', 'Laos');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('LV', 'LVA', 428, 'Latvia ', 'Latvija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('LB', 'LBN', 422, 'Lebanon ', 'Libanon');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('LS', 'LSO', 426, 'Lesotho ', 'Lesoto');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('LR', 'LBR', 430, 'Liberia ', 'Liberija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('LY ', 'LBY', 434, 'Libya ', 'Libija', 'Bivši ISO naziv države: Libyan Arab Jamahiriya.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('LI', 'LIE', 438, 'Liechtenstein ', 'Lihtenštajn');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('LT', 'LTU', 440, 'Lithuania ', 'Litva');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('LU', 'LUX', 442, 'Luxembourg ', 'Luksemburg');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('MO', 'MAC', 446, 'Macao ', 'Makao', 'Bivši ISO naziv države: Macau.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('MK', 'MKD', 807, 'Macedonia, the former Yugoslav Republic of ', 'Makedonija', 'ISO naziv države glede na spor o nazivu države. Uradno domače ime države: Republika Makedonija.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('MG', 'MDG', 450, 'Madagascar ', 'Madagaskar');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('MW', 'MWI', 454, 'Malawi ', 'Malavi');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('MY', 'MYS', 458, 'Malaysia ', 'Malezija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('MV', 'MDV', 462, 'Maldives ', 'Maldivi');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('ML', 'MLI', 466, 'Mali ', 'Mali');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('MT', 'MLT', 470, 'Malta ', 'Malta');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('MH', 'MHL', 584, 'Marshall Islands ', 'Maršalovi otoki', 'Majhno otočje v Tihem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('MQ', 'MTQ', 474, 'Martinique ', 'Martinik', 'Čezmorski otok Francije v malih Antilih v Karibsekm morju.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('MR', 'MRT', 478, 'Mauritania ', 'Mavretanija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('MU', 'MUS', 480, 'Mauritius ', 'Mauricius (Moris)', 'Domačini v kreolščini imenujejo otok: Moris.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('YT', 'MYT', 175, 'Mayotte ', 'Francoska skupnost Mejot', 'Čezmorska skupnost Francije ob vzhodni obali Afrike.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('MX', 'MEX', 484, 'Mexico ', 'Mehika');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('FM', 'FSM', 583, 'Micronesia, Federated States of ', 'Mikronezija', 'Bivši ISO naziv države: Micronesia. Nahaja se v Tihem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('MD', 'MDA', 498, 'Moldova, Republic of ', 'Moldavija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('MC', 'MCO', 492, 'Monaco ', 'Monako');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('MN', 'MNG', 496, 'Mongolia ', 'Mongolija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('ME', 'MNE', 499, 'Montenegro ', 'Črna Gora');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('MS', 'MSR', 500, 'Montserrat ', 'Montserat', 'Otok v Antilih v Karibskem morju odvisen od Velike Britanije.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('MA', 'MAR', 504, 'Morocco ', 'Maroko');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('MZ', 'MOZ', 508, 'Mozambique ', 'Mozambik');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('MM', 'MMR', 104, 'Myanmar ', 'Mjanmar', 'Bivši naziv: Burma (BU).');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('NA', 'NAM', 516, 'Namibia ', 'Namibija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('NR', 'NRU', 520, 'Nauru ', 'Nauru', 'Otoška država v Južnem Tihem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('NP', 'NPL', 524, 'Nepal ', 'Nepal');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('NL', 'NLD', 528, 'Netherlands ', 'Nizozemska');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('NC', 'NCL', 540, 'New Caledonia ', 'Nova Kaledonija', 'Čezmorsko otočje Francije v Pacifiku.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('NZ', 'NZL', 554, 'New Zealand ', 'Nova Zelandija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('NI', 'NIC', 558, 'Nicaragua ', 'Nikaragva');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('NE', 'NER', 562, 'Niger ', 'Niger ');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('NG', 'NGA', 566, 'Nigeria ', 'Nigerija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('NU', 'NIU', 570, 'Niue ', 'Niu', 'Otoška država v Južnem Tihem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('NF', 'NFK', 574, 'Norfolk Island ', 'Otok Norflok', 'Del Avstralije s samoupravo.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('MP', 'MNP', 580, 'Northern Mariana Islands ', 'Severni Marianski otoki', 'Ameriško otočje v severnem Tihem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('NO', 'NOR', 578, 'Norway ', 'Norveška');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('OM', 'OMN', 512, 'Oman ', 'Oman');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('PK', 'PAK', 586, 'Pakistan ', 'Pakistan');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('PW', 'PLW', 585, 'Palau ', 'Palau ', 'Majhna otoška država v Tihem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('PS', 'PSE', 275, 'Palestinian Territory, Occupied ', 'Palestina', 'Sestavljena iz Zahodnega brega in Gaze.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('PA', 'PAN', 591, 'Panama ', 'Panama');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('PG', 'PNG', 598, 'Papua New Guinea ', 'Papua Nova Gvineja');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('PY', 'PRY', 600, 'Paraguay ', 'Paragvaj');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('PE', 'PER', 604, 'Peru ', 'Peru');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('PH', 'PHL', 608, 'Philippines ', 'Filipini');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('PN', 'PCN', 612, 'Pitcairn ', 'Pitcairnovi otoki', 'Čezmorsko otočje Velike Britanije v Tihem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('PL', 'POL', 616, 'Poland ', 'Poljska');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('PT', 'PRT', 620, 'Portugal ', 'Portugalska');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('PR', 'PRI', 630, 'Puerto Rico ', 'Portoriko');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('QA', 'QAT', 634, 'Qatar ', 'Katar');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('RE', 'REU', 638, 'Réunion ', 'Francoska skupnost Reunion', 'Čezmorska otoška skupnost Francije v Indijskem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('RO', 'ROU', 642, 'Romania ', 'Romunija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('RU', 'RUS', 643, 'Russian Federation ', 'Ruska federacija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('RW', 'RWA', 646, 'Rwanda ', 'Ruanda');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('BL', 'BLM', 652, 'Saint Barthélemy ', 'Sveti Bartolomej', 'Čezmosrksa skupnost Francije.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('SH', 'SHN', 654, 'Saint Helena, Ascension and Tristan da Cunha ', 'Sveta Helena', 'Čezmorsko ozemlje Sveta Helena Velike Britanije v Atlantskem oceanu. Bivši ISO naziv države: Saint Helena.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('KN', 'KNA', 659, 'Saint Kitts and Nevis ', 'Sveti Kits in Nevis', 'Otoška državica v karibskih Malih Antilih. Bivši ISO naziv države: Saint Kitts-Nevis-Anguilla.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('LC', 'LCA', 662, 'Saint Lucia ', 'Sveta Lucija', 'Otoška država v južnem Karibskem morju.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('MF', 'MAF', 663, 'Saint Martin (French part) ', 'Otok svetega Martina', 'Čezmorsko otočje Francije v Karibskem morju. Nizozmski del otoka Sv. Martina ima kodo SX.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('PM', 'SPM', 666, 'Saint Pierre and Miquelon ', 'Sveta Pierre in Miquelon', 'Čezmorsko otočje Francije ob Kanadi in Grenlandiji.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('VC', 'VCT', 670, 'Saint Vincent and the Grenadines ', 'Sveti Vincent in Grenadini', 'Majhna otoška država v Karibskem otočju.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('WS', 'WSM', 882, 'Samoa ', 'Samoa', 'Koda nastala po bivšem nazivu: Western Samoa (Zahodna Samoa).');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SM', 'SMR', 674, 'San Marino ', 'San Marino');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('ST', 'STP', 678, 'Sao Tome and Principe ', 'Sao Tome in Principe', 'Majhna otoška država v Gvinejskem zalivu ob Afriki.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SA', 'SAU', 682, 'Saudi Arabia ', 'Savdska Arabija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SN', 'SEN', 686, 'Senegal ', 'Senegal');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('RS', 'SRB', 688, 'Serbia ', 'Srbija', 'Koda po uradnem nazivu: Republika Srbija.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SC', 'SYC', 690, 'Seychelles ', 'Sejšeli');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SL', 'SLE', 694, 'Sierra Leone ', 'Siera Leone');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SG', 'SGP', 702, 'Singapore ', 'Singapur');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('SX', 'SXM', 534, 'Sint Maarten (Dutch part) ', 'Otok svetega.Martina (Nizozemska)', 'Francoski del otoka Sv. Martina ima ISO kodo MF. Nahaja se v Karibskem morju.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('SK', 'SVK', 703, 'Slovakia ', 'Slovaška', 'SK je prej predstavljal: Sikkim.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SI', 'SVN', 705, 'Slovenia ', 'Slovenija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('SB', 'SLB', 090, 'Solomon Islands ', 'Solomonovi otoki', 'Koda izhaja iz starega naziva: British Solomon Islands.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SO', 'SOM', 706, 'Somalia ', 'Somalija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('ZA', 'ZAF', 710, 'South Africa ', 'Južna afrika', 'Koda iz naziva v nizozemščini: Zuid-Afrika.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('GS', 'SGS', 239, 'South Georgia and the South Sandwich Islands ', 'Južna Georgia in Južni Sandwichevi otoki', 'Čezmorsko otočje Velike Britanije na jugu Atlantskega oceana.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SS', 'SSD', 728, 'South Sudan ', 'Južni Sudan');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('ES', 'ESP', 724, 'Spain ', 'Španija', 'Koda po nazivu v spanščini: España.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('LK', 'LKA', 144, 'Sri Lanka ', 'Šri Lanka');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SD', 'SDN', 729, 'Sudan ', 'Sudan');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SR', 'SUR', 740, 'Suriname ', 'Surinam');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('SJ', 'SJM', 744, 'Svalbard and Jan Mayen ', 'Svalbard in Jan Majen ', 'Sestavljata ga dva arktična ozemlja pod suverenostjo Norveške: Svalbardski otoki in otok Jan Mayen.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SZ', 'SWZ', 748, 'Swaziland ', 'Svazi');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SE', 'SWE', 752, 'Sweden ', 'Švedska');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('CH', 'CHE', 756, 'Switzerland ', 'Švica', 'Koda je narejena po nazivu v latinščini: Confoederatio Helvetica.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('SY', 'SYR', 760, 'Syrian Arab Republic ', 'Sirija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('TW', 'TWN', 158, 'Taiwan, Province of China ', 'Tajvan');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('TJ', 'TJK', 762, 'Tajikistan ', 'Tadžikistan');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('TZ', 'TZA', 834, 'Tanzania, United Republic of ', 'Tanzanija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('TH', 'THA', 764, 'Thailand ', 'Tajska');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('TL', 'TLS', 626, 'Timor-Leste ', 'Vzhodni Timor', 'Bivši naziv: East Timor (TP). Majhna otoška država v JV Aziji.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('TG', 'TGO', 768, 'Togo ', 'Togo');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('TK', 'TKL', 772, 'Tokelau ', 'Tokelau', 'Trije koralni otoki pod upravo Nove Zelandije.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('TO', 'TON', 776, 'Tonga ', 'Tonga', 'Majhna otoška država v Tihem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('TT', 'TTO', 780, 'Trinidad and Tobago ', 'Trinidad in Tobago');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('TN', 'TUN', 788, 'Tunisia ', 'Tunizija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('TR', 'TUR', 792, 'Turkey ', 'Turčija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('TM', 'TKM', 795, 'Turkmenistan ', 'Turkmenistan');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('TC', 'TCA', 796, 'Turks and Caicos Islands ', 'Tirški in Kajkoški otoki', 'Čezmorska skupnost Velike Britanije v Karibskem morju.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('TV', 'TUV', 798, 'Tuvalu ', 'Tuvalu', 'Majhna otoška država v Tihem oceanu.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('UG', 'UGA', 800, 'Uganda ', 'Uganda');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('UA', 'UKR', 804, 'Ukraine ', 'Ukrajina', 'Bivši ISO naziv države: Ukrainian SSR. ');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('AE', 'ARE', 784, 'United Arab Emirates ', 'Združeni Arabski Emirati');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('GB', 'GBR', 826, 'United Kingdom ', 'Velika Britanija', 'Koda po nazivu: Great Britain (iz uradnega naziva: United Kingdom of Great Britain and Northern Ireland). ');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('US', 'USA', 840, 'United States ', 'Združene države Amerike');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('UM', 'UMI', 581, 'United States Minor Outlying Islands ', 'ZDA zunanji otoki', 'Sestavljeno iz devetih manjših otokov ZDA: Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Islands, Navassa Island, Palmyra Atoll, and Wake Island.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('UY', 'URY', 858, 'Uruguay ', 'Urugvaj');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('UZ', 'UZB', 860, 'Uzbekistan ', 'Uzbekistan');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('VU', 'VUT', 548, 'Vanuatu ', 'Republika Vanuatu', 'Stari naziv: New Hebrides (NH).');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('VE', 'VEN', 862, 'Venezuela, Bolivarian Republic of ', 'Venezuela');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('VN', 'VNM', 704, 'Viet Nam ', 'Vietnam');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('VG', 'VGB', 092, 'Virgin Islands, British ', 'Britanski Deviški otoki', 'Čezmorska skupnost Velike Britanije v Karibskem morju.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('VI', 'VIR', 850, 'Virgin Islands, U.S. ', 'Ameriški Deviški otoki');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('WF', 'WLF', 876, 'Wallis and Futuna ', 'Otočje Valis in Futuna', 'Čezmorska skupnost Francije v Pacifiku.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('EH', 'ESH', 732, 'Western Sahara ', 'Zahodna Sahara', 'Bivši ISO naziv države: Spanish Sahara (koda po španskem nazivu: Sahara español).');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('YE', 'YEM', 887, 'Yemen ', 'Jemen', 'Bivši ISO naziv države: Republic of Yemen, koda se je uporabljala za Severni Jemen pred letom 1990.');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv) VALUES ('ZM', 'ZMB', 894, 'Zambia ', 'Zambija');
INSERT INTO drzava (iso_koda, iso_3_koda, numericna_oznaka, iso_naziv, slovenski_naziv, opombe) VALUES ('ZW', 'ZWE', 716, 'Zimbabwe ', 'Zimbabve', 'Naziv se je spremenil iz: Suthern Rhodesia (RH, Južna Rodezija).');
