INSERT INTO obcina (sifra, ime) VALUES (213.0, 'Ankaran');
INSERT INTO obcina (sifra, ime) VALUES (1.0, 'Ajdovščina ');
INSERT INTO obcina (sifra, ime) VALUES (195.0, 'Apače ');
INSERT INTO obcina (sifra, ime) VALUES (2.0, 'Beltinci ');
INSERT INTO obcina (sifra, ime) VALUES (148.0, 'Benedikt ');
INSERT INTO obcina (sifra, ime) VALUES (149.0, 'Bistrica ob Sotli ');
INSERT INTO obcina (sifra, ime) VALUES (3.0, 'Bled ');
INSERT INTO obcina (sifra, ime) VALUES (150.0, 'Bloke ');
INSERT INTO obcina (sifra, ime) VALUES (4.0, 'Bohinj ');
INSERT INTO obcina (sifra, ime) VALUES (5.0, 'Borovnica ');
INSERT INTO obcina (sifra, ime) VALUES (6.0, 'Bovec ');
INSERT INTO obcina (sifra, ime) VALUES (151.0, 'Braslovče ');
INSERT INTO obcina (sifra, ime) VALUES (7.0, 'Brda ');
INSERT INTO obcina (sifra, ime) VALUES (8.0, 'Brezovica ');
INSERT INTO obcina (sifra, ime) VALUES (9.0, 'Brežice ');
INSERT INTO obcina (sifra, ime) VALUES (152.0, 'Cankova ');
INSERT INTO obcina (sifra, ime) VALUES (11.0, 'Celje ');
INSERT INTO obcina (sifra, ime) VALUES (12.0, 'Cerklje na Gorenjskem ');
INSERT INTO obcina (sifra, ime) VALUES (13.0, 'Cerknica ');
INSERT INTO obcina (sifra, ime) VALUES (14.0, 'Cerkno ');
INSERT INTO obcina (sifra, ime) VALUES (153.0, 'Cerkvenjak ');
INSERT INTO obcina (sifra, ime) VALUES (196.0, 'Cirkulane ');
INSERT INTO obcina (sifra, ime) VALUES (15.0, 'Črenšovci ');
INSERT INTO obcina (sifra, ime) VALUES (16.0, 'Črna na Koroškem ');
INSERT INTO obcina (sifra, ime) VALUES (17.0, 'Črnomelj ');
INSERT INTO obcina (sifra, ime) VALUES (18.0, 'Destrnik ');
INSERT INTO obcina (sifra, ime) VALUES (19.0, 'Divača ');
INSERT INTO obcina (sifra, ime) VALUES (154.0, 'Dobje ');
INSERT INTO obcina (sifra, ime) VALUES (20.0, 'Dobrepolje ');
INSERT INTO obcina (sifra, ime) VALUES (155.0, 'Dobrna ');
INSERT INTO obcina (sifra, ime) VALUES (21.0, 'Dobrova - Polhov Gradec ');
INSERT INTO obcina (sifra, ime) VALUES (156.0, 'Dobrovnik ');
INSERT INTO obcina (sifra, ime) VALUES (22.0, 'Dol pri Ljubljani ');
INSERT INTO obcina (sifra, ime) VALUES (157.0, 'Dolenjske Toplice ');
INSERT INTO obcina (sifra, ime) VALUES (23.0, 'Domžale ');
INSERT INTO obcina (sifra, ime) VALUES (24.0, 'Dornava ');
INSERT INTO obcina (sifra, ime) VALUES (25.0, 'Dravograd ');
INSERT INTO obcina (sifra, ime) VALUES (26.0, 'Duplek ');
INSERT INTO obcina (sifra, ime) VALUES (27.0, 'Gorenja vas - Poljane ');
INSERT INTO obcina (sifra, ime) VALUES (28.0, 'Gorišnica ');
INSERT INTO obcina (sifra, ime) VALUES (207.0, 'Gorje ');
INSERT INTO obcina (sifra, ime) VALUES (29.0, 'Gornja Radgona ');
INSERT INTO obcina (sifra, ime) VALUES (30.0, 'Gornji Grad ');
INSERT INTO obcina (sifra, ime) VALUES (31.0, 'Gornji Petrovci ');
INSERT INTO obcina (sifra, ime) VALUES (158.0, 'Grad ');
INSERT INTO obcina (sifra, ime) VALUES (32.0, 'Grosuplje ');
INSERT INTO obcina (sifra, ime) VALUES (159.0, 'Hajdina ');
INSERT INTO obcina (sifra, ime) VALUES (160.0, 'Hoče - Slivnica ');
INSERT INTO obcina (sifra, ime) VALUES (161.0, 'Hodoš ');
INSERT INTO obcina (sifra, ime) VALUES (162.0, 'Horjul ');
INSERT INTO obcina (sifra, ime) VALUES (34.0, 'Hrastnik ');
INSERT INTO obcina (sifra, ime) VALUES (35.0, 'Hrpelje - Kozina ');
INSERT INTO obcina (sifra, ime) VALUES (36.0, 'Idrija ');
INSERT INTO obcina (sifra, ime) VALUES (37.0, 'Ig ');
INSERT INTO obcina (sifra, ime) VALUES (38.0, 'Ilirska Bistrica ');
INSERT INTO obcina (sifra, ime) VALUES (39.0, 'Ivančna Gorica ');
INSERT INTO obcina (sifra, ime) VALUES (40.0, 'Izola ');
INSERT INTO obcina (sifra, ime) VALUES (41.0, 'Jesenice ');
INSERT INTO obcina (sifra, ime) VALUES (163.0, 'Jezersko ');
INSERT INTO obcina (sifra, ime) VALUES (42.0, 'Juršinci ');
INSERT INTO obcina (sifra, ime) VALUES (43.0, 'Kamnik ');
INSERT INTO obcina (sifra, ime) VALUES (44.0, 'Kanal ');
INSERT INTO obcina (sifra, ime) VALUES (45.0, 'Kidričevo ');
INSERT INTO obcina (sifra, ime) VALUES (46.0, 'Kobarid ');
INSERT INTO obcina (sifra, ime) VALUES (47.0, 'Kobilje ');
INSERT INTO obcina (sifra, ime) VALUES (48.0, 'Kočevje ');
INSERT INTO obcina (sifra, ime) VALUES (49.0, 'Komen ');
INSERT INTO obcina (sifra, ime) VALUES (164.0, 'Komenda ');
INSERT INTO obcina (sifra, ime) VALUES (50.0, 'Koper ');
INSERT INTO obcina (sifra, ime) VALUES (197.0, 'Kostanjevica na Krki ');
INSERT INTO obcina (sifra, ime) VALUES (165.0, 'Kostel ');
INSERT INTO obcina (sifra, ime) VALUES (51.0, 'Kozje ');
INSERT INTO obcina (sifra, ime) VALUES (52.0, 'Kranj ');
INSERT INTO obcina (sifra, ime) VALUES (53.0, 'Kranjska Gora ');
INSERT INTO obcina (sifra, ime) VALUES (166.0, 'Križevci ');
INSERT INTO obcina (sifra, ime) VALUES (54.0, 'Krško ');
INSERT INTO obcina (sifra, ime) VALUES (55.0, 'Kungota ');
INSERT INTO obcina (sifra, ime) VALUES (56.0, 'Kuzma ');
INSERT INTO obcina (sifra, ime) VALUES (57.0, 'Laško ');
INSERT INTO obcina (sifra, ime) VALUES (58.0, 'Lenart ');
INSERT INTO obcina (sifra, ime) VALUES (59.0, 'Lendava ');
INSERT INTO obcina (sifra, ime) VALUES (60.0, 'Litija ');
INSERT INTO obcina (sifra, ime) VALUES (61.0, 'Ljubljana ');
INSERT INTO obcina (sifra, ime) VALUES (62.0, 'Ljubno ');
INSERT INTO obcina (sifra, ime) VALUES (63.0, 'Ljutomer ');
INSERT INTO obcina (sifra, ime) VALUES (208.0, 'Log - Dragomer ');
INSERT INTO obcina (sifra, ime) VALUES (64.0, 'Logatec ');
INSERT INTO obcina (sifra, ime) VALUES (65.0, 'Loška dolina ');
INSERT INTO obcina (sifra, ime) VALUES (66.0, 'Loški Potok ');
INSERT INTO obcina (sifra, ime) VALUES (167.0, 'Lovrenc na Pohorju ');
INSERT INTO obcina (sifra, ime) VALUES (67.0, 'Luče ');
INSERT INTO obcina (sifra, ime) VALUES (68.0, 'Lukovica ');
INSERT INTO obcina (sifra, ime) VALUES (69.0, 'Majšperk ');
INSERT INTO obcina (sifra, ime) VALUES (198.0, 'Makole ');
INSERT INTO obcina (sifra, ime) VALUES (70.0, 'Maribor ');
INSERT INTO obcina (sifra, ime) VALUES (168.0, 'Markovci ');
INSERT INTO obcina (sifra, ime) VALUES (71.0, 'Medvode ');
INSERT INTO obcina (sifra, ime) VALUES (72.0, 'Mengeš ');
INSERT INTO obcina (sifra, ime) VALUES (73.0, 'Metlika ');
INSERT INTO obcina (sifra, ime) VALUES (74.0, 'Mežica ');
INSERT INTO obcina (sifra, ime) VALUES (169.0, 'Miklavž na Dravskem polju');
INSERT INTO obcina (sifra, ime) VALUES (75.0, 'Miren - Kostanjevica ');
INSERT INTO obcina (sifra, ime) VALUES (212.0, 'Mirna ');
INSERT INTO obcina (sifra, ime) VALUES (170.0, 'Mirna Peč ');
INSERT INTO obcina (sifra, ime) VALUES (76.0, 'Mislinja ');
INSERT INTO obcina (sifra, ime) VALUES (199.0, 'Mokronog - Trebelno ');
INSERT INTO obcina (sifra, ime) VALUES (77.0, 'Moravče ');
INSERT INTO obcina (sifra, ime) VALUES (78.0, 'Moravske Toplice ');
INSERT INTO obcina (sifra, ime) VALUES (79.0, 'Mozirje ');
INSERT INTO obcina (sifra, ime) VALUES (80.0, 'Murska Sobota ');
INSERT INTO obcina (sifra, ime) VALUES (81.0, 'Muta ');
INSERT INTO obcina (sifra, ime) VALUES (82.0, 'Naklo ');
INSERT INTO obcina (sifra, ime) VALUES (83.0, 'Nazarje ');
INSERT INTO obcina (sifra, ime) VALUES (84.0, 'Nova Gorica ');
INSERT INTO obcina (sifra, ime) VALUES (85.0, 'Novo mesto ');
INSERT INTO obcina (sifra, ime) VALUES (86.0, 'Odranci ');
INSERT INTO obcina (sifra, ime) VALUES (171.0, 'Oplotnica ');
INSERT INTO obcina (sifra, ime) VALUES (87.0, 'Ormož ');
INSERT INTO obcina (sifra, ime) VALUES (88.0, 'Osilnica ');
INSERT INTO obcina (sifra, ime) VALUES (89.0, 'Pesnica ');
INSERT INTO obcina (sifra, ime) VALUES (90.0, 'Piran ');
INSERT INTO obcina (sifra, ime) VALUES (91.0, 'Pivka ');
INSERT INTO obcina (sifra, ime) VALUES (92.0, 'Podčetrtek ');
INSERT INTO obcina (sifra, ime) VALUES (172.0, 'Podlehnik ');
INSERT INTO obcina (sifra, ime) VALUES (93.0, 'Podvelka ');
INSERT INTO obcina (sifra, ime) VALUES (200.0, 'Poljčane ');
INSERT INTO obcina (sifra, ime) VALUES (173.0, 'Polzela ');
INSERT INTO obcina (sifra, ime) VALUES (94.0, 'Postojna ');
INSERT INTO obcina (sifra, ime) VALUES (174.0, 'Prebold ');
INSERT INTO obcina (sifra, ime) VALUES (95.0, 'Preddvor ');
INSERT INTO obcina (sifra, ime) VALUES (175.0, 'Prevalje ');
INSERT INTO obcina (sifra, ime) VALUES (96.0, 'Ptuj ');
INSERT INTO obcina (sifra, ime) VALUES (97.0, 'Puconci ');
INSERT INTO obcina (sifra, ime) VALUES (98.0, 'Rače - Fram ');
INSERT INTO obcina (sifra, ime) VALUES (99.0, 'Radeče ');
INSERT INTO obcina (sifra, ime) VALUES (100.0, 'Radenci ');
INSERT INTO obcina (sifra, ime) VALUES (101.0, 'Radlje ob Dravi ');
INSERT INTO obcina (sifra, ime) VALUES (102.0, 'Radovljica ');
INSERT INTO obcina (sifra, ime) VALUES (103.0, 'Ravne na Koroškem ');
INSERT INTO obcina (sifra, ime) VALUES (176.0, 'Razkrižje ');
INSERT INTO obcina (sifra, ime) VALUES (209.0, 'Rečica ob Savinji ');
INSERT INTO obcina (sifra, ime) VALUES (201.0, 'Renče - Vogrsko ');
INSERT INTO obcina (sifra, ime) VALUES (104.0, 'Ribnica ');
INSERT INTO obcina (sifra, ime) VALUES (177.0, 'Ribnica na Pohorju ');
INSERT INTO obcina (sifra, ime) VALUES (106.0, 'Rogaška Slatina ');
INSERT INTO obcina (sifra, ime) VALUES (105.0, 'Rogašovci ');
INSERT INTO obcina (sifra, ime) VALUES (107.0, 'Rogatec ');
INSERT INTO obcina (sifra, ime) VALUES (108.0, 'Ruše ');
INSERT INTO obcina (sifra, ime) VALUES (178.0, 'Selnica ob Dravi ');
INSERT INTO obcina (sifra, ime) VALUES (109.0, 'Semič ');
INSERT INTO obcina (sifra, ime) VALUES (110.0, 'Sevnica ');
INSERT INTO obcina (sifra, ime) VALUES (111.0, 'Sežana ');
INSERT INTO obcina (sifra, ime) VALUES (112.0, 'Slovenj Gradec ');
INSERT INTO obcina (sifra, ime) VALUES (113.0, 'Slovenska Bistrica ');
INSERT INTO obcina (sifra, ime) VALUES (114.0, 'Slovenske Konjice ');
INSERT INTO obcina (sifra, ime) VALUES (179.0, 'Sodražica ');
INSERT INTO obcina (sifra, ime) VALUES (180.0, 'Solčava ');
INSERT INTO obcina (sifra, ime) VALUES (202.0, 'Središče ob Dravi ');
INSERT INTO obcina (sifra, ime) VALUES (115.0, 'Starše ');
INSERT INTO obcina (sifra, ime) VALUES (203.0, 'Straža ');
INSERT INTO obcina (sifra, ime) VALUES (204.0, 'Sv. Trojica v Slov. Goricah ');
INSERT INTO obcina (sifra, ime) VALUES (181.0, 'Sveta Ana ');
INSERT INTO obcina (sifra, ime) VALUES (182.0, 'Sveti Andraž v Slov. Goricah ');
INSERT INTO obcina (sifra, ime) VALUES (116.0, 'Sveti Jurij ob Ščavnici ');
INSERT INTO obcina (sifra, ime) VALUES (210.0, 'Sveti Jurij v Slov. Goricah ');
INSERT INTO obcina (sifra, ime) VALUES (205.0, 'Sveti Tomaž ');
INSERT INTO obcina (sifra, ime) VALUES (33.0, 'Šalovci ');
INSERT INTO obcina (sifra, ime) VALUES (183.0, 'Šempeter - Vrtojba ');
INSERT INTO obcina (sifra, ime) VALUES (117.0, 'Šenčur ');
INSERT INTO obcina (sifra, ime) VALUES (118.0, 'Šentilj ');
INSERT INTO obcina (sifra, ime) VALUES (119.0, 'Šentjernej ');
INSERT INTO obcina (sifra, ime) VALUES (120.0, 'Šentjur pri Celju ');
INSERT INTO obcina (sifra, ime) VALUES (211.0, 'Šentrupert ');
INSERT INTO obcina (sifra, ime) VALUES (121.0, 'Škocjan ');
INSERT INTO obcina (sifra, ime) VALUES (122.0, 'Škofja Loka ');
INSERT INTO obcina (sifra, ime) VALUES (123.0, 'Škofljica ');
INSERT INTO obcina (sifra, ime) VALUES (124.0, 'Šmarje pri Jelšah ');
INSERT INTO obcina (sifra, ime) VALUES (206.0, 'Šmarješke Toplice ');
INSERT INTO obcina (sifra, ime) VALUES (125.0, 'Šmartno ob Paki ');
INSERT INTO obcina (sifra, ime) VALUES (194.0, 'Šmartno pri Litiji ');
INSERT INTO obcina (sifra, ime) VALUES (126.0, 'Šoštanj ');
INSERT INTO obcina (sifra, ime) VALUES (127.0, 'Štore ');
INSERT INTO obcina (sifra, ime) VALUES (184.0, 'Tabor ');
INSERT INTO obcina (sifra, ime) VALUES (10.0, 'Tišina ');
INSERT INTO obcina (sifra, ime) VALUES (128.0, 'Tolmin ');
INSERT INTO obcina (sifra, ime) VALUES (129.0, 'Trbovlje ');
INSERT INTO obcina (sifra, ime) VALUES (130.0, 'Trebnje ');
INSERT INTO obcina (sifra, ime) VALUES (185.0, 'Trnovska vas ');
INSERT INTO obcina (sifra, ime) VALUES (186.0, 'Trzin ');
INSERT INTO obcina (sifra, ime) VALUES (131.0, 'Tržič ');
INSERT INTO obcina (sifra, ime) VALUES (132.0, 'Turnišče ');
INSERT INTO obcina (sifra, ime) VALUES (133.0, 'Velenje ');
INSERT INTO obcina (sifra, ime) VALUES (187.0, 'Velika Polana ');
INSERT INTO obcina (sifra, ime) VALUES (134.0, 'Velike Lašče ');
INSERT INTO obcina (sifra, ime) VALUES (188.0, 'Veržej ');
INSERT INTO obcina (sifra, ime) VALUES (135.0, 'Videm ');
INSERT INTO obcina (sifra, ime) VALUES (136.0, 'Vipava ');
INSERT INTO obcina (sifra, ime) VALUES (137.0, 'Vitanje ');
INSERT INTO obcina (sifra, ime) VALUES (138.0, 'Vodice ');
INSERT INTO obcina (sifra, ime) VALUES (139.0, 'Vojnik ');
INSERT INTO obcina (sifra, ime) VALUES (189.0, 'Vransko ');
INSERT INTO obcina (sifra, ime) VALUES (140.0, 'Vrhnika ');
INSERT INTO obcina (sifra, ime) VALUES (141.0, 'Vuzenica ');
INSERT INTO obcina (sifra, ime) VALUES (142.0, 'Zagorje ob Savi ');
INSERT INTO obcina (sifra, ime) VALUES (143.0, 'Zavrč ');
INSERT INTO obcina (sifra, ime) VALUES (144.0, 'Zreče ');
INSERT INTO obcina (sifra, ime) VALUES (190.0, 'Žalec ');
INSERT INTO obcina (sifra, ime) VALUES (146.0, 'Železniki ');
INSERT INTO obcina (sifra, ime) VALUES (191.0, 'Žetale ');
INSERT INTO obcina (sifra, ime) VALUES (147.0, 'Žiri ');
INSERT INTO obcina (sifra, ime) VALUES (192.0, 'Žirovnica ');
INSERT INTO obcina (sifra, ime) VALUES (193.0, 'Žužemberk ');