INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8341, 'Adlešiči');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5270, 'Ajdovščina');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6280, 'Ankaran/Ancarano');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9253, 'Apače');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8253, 'Artiče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4275, 'Begunje na Gorenjskem');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1382, 'Begunje pri Cerknici');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9231, 'Beltinci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2234, 'Benedikt');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2345, 'Bistrica ob Dravi');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3256, 'Bistrica ob Sotli');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8259, 'Bizeljsko');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1223, 'Blagovica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8283, 'Blanca');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4260, 'Bled');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4273, 'Blejska Dobrava');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9265, 'Bodonci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9222, 'Bogojina');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4263, 'Bohinjska Bela');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4264, 'Bohinjska Bistrica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4265, 'Bohinjsko jezero');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1353, 'Borovnica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8294, 'Boštanj');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5230, 'Bovec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5295, 'Branik');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3314, 'Braslovče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5223, 'Breginj');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8280, 'Brestanica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2354, 'Bresternica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4243, 'Brezje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1351, 'Brezovica pri Ljubljani');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8250, 'Brežice');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4210, 'Brnik - Aerodrom');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8321, 'Brusnice');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3255, 'Buče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8276, 'Bučka ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9261, 'Cankova');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3000, 'Celje ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3001, 'Celje - poštni predali');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4207, 'Cerklje na Gorenjskem');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8263, 'Cerklje ob Krki');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1380, 'Cerknica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5282, 'Cerkno');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2236, 'Cerkvenjak');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2215, 'Ceršak');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2326, 'Cirkovce');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2282, 'Cirkulane');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5273, 'Col');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8251, 'Čatež ob Savi');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1413, 'Čemšenik');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5253, 'Čepovan');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9232, 'Črenšovci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2393, 'Črna na Koroškem');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6275, 'Črni Kal');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5274, 'Črni Vrh nad Idrijo');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5262, 'Črniče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8340, 'Črnomelj');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6271, 'Dekani');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5210, 'Deskle');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2253, 'Destrnik');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6215, 'Divača');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1233, 'Dob');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3224, 'Dobje pri Planini');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8257, 'Dobova');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1423, 'Dobovec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5263, 'Dobravlje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3204, 'Dobrna');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8211, 'Dobrnič');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1356, 'Dobrova');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9223, 'Dobrovnik/Dobronak ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5212, 'Dobrovo v Brdih');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1431, 'Dol pri Hrastniku');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1262, 'Dol pri Ljubljani');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1273, 'Dole pri Litiji');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1331, 'Dolenja vas');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8350, 'Dolenjske Toplice');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1230, 'Domžale');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2252, 'Dornava');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5294, 'Dornberk');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1319, 'Draga');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8343, 'Dragatuš');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3222, 'Dramlje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2370, 'Dravograd');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4203, 'Duplje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6221, 'Dutovlje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8361, 'Dvor');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2343, 'Fala');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9208, 'Fokovci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2313, 'Fram');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3213, 'Frankolovo');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1274, 'Gabrovka');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8254, 'Globoko');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5275, 'Godovič');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4204, 'Golnik');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3303, 'Gomilsko');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4224, 'Gorenja vas');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3263, 'Gorica pri Slivnici');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2272, 'Gorišnica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9250, 'Gornja Radgona');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3342, 'Gornji Grad');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4282, 'Gozd Martuljek');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6272, 'Gračišče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9264, 'Grad');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8332, 'Gradac');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1384, 'Grahovo');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5242, 'Grahovo ob Bači');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5251, 'Grgar');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3302, 'Griže');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3231, 'Grobelno');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1290, 'Grosuplje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2288, 'Hajdina');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8362, 'Hinje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2311, 'Hoče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9205, 'Hodoš/Hodos');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1354, 'Horjul');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1372, 'Hotedršica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1430, 'Hrastnik');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6225, 'Hruševje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4276, 'Hrušica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5280, 'Idrija');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1292, 'Ig');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6250, 'Ilirska Bistrica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6251, 'Ilirska Bistrica-Trnovo');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1295, 'Ivančna Gorica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2259, 'Ivanjkovci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1411, 'Izlake');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6310, 'Izola/Isola');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2222, 'Jakobski Dol');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2221, 'Jarenina');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6254, 'Jelšane');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4270, 'Jesenice');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8261, 'Jesenice na Dolenjskem');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3273, 'Jurklošter');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2223, 'Jurovski Dol');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2256, 'Juršinci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5214, 'Kal nad Kanalom');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3233, 'Kalobje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4246, 'Kamna Gorica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2351, 'Kamnica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1241, 'Kamnik');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5213, 'Kanal');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8258, 'Kapele');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2362, 'Kapla');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2325, 'Kidričevo');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1412, 'Kisovec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6253, 'Knežak');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5222, 'Kobarid');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9227, 'Kobilje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1330, 'Kočevje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1338, 'Kočevska Reka');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2276, 'Kog');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5211, 'Kojsko');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6223, 'Komen');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1218, 'Komenda');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6000, 'Koper/Capodistria ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6001, 'Koper/Capodistria - poštni predali');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8282, 'Koprivnica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5296, 'Kostanjevica na Krasu');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8311, 'Kostanjevica na Krki');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1336, 'Kostel');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6256, 'Košana');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2394, 'Kotlje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6240, 'Kozina');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3260, 'Kozje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4000, 'Kranj ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4001, 'Kranj - poštni predali');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4280, 'Kranjska Gora');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1281, 'Kresnice');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4294, 'Križe');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9206, 'Križevci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9242, 'Križevci pri Ljutomeru');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1301, 'Krka');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8296, 'Krmelj');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4245, 'Kropa');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8262, 'Krška vas');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8270, 'Krško');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9263, 'Kuzma');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2318, 'Laporje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3270, 'Laško');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1219, 'Laze v Tuhinju');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2230, 'Lenart v Slovenskih goricah');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9220, 'Lendava/Lendva');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4248, 'Lesce');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3261, 'Lesično');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8273, 'Leskovec pri Krškem');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2372, 'Libeliče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2341, 'Limbuš');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1270, 'Litija');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3202, 'Ljubečna');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1000, 'Ljubljana ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1001, 'Ljubljana - poštni predali');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1231, 'Ljubljana - Črnuče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1261, 'Ljubljana - Dobrunje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1260, 'Ljubljana - Polje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1210, 'Ljubljana - Šentvid');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1211, 'Ljubljana - Šmartno');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3333, 'Ljubno ob Savinji');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9240, 'Ljutomer');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3215, 'Loče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5231, 'Log pod Mangartom');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1358, 'Log pri Brezovici');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1370, 'Logatec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1371, 'Logatec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1434, 'Loka pri Zidanem Mostu');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3223, 'Loka pri Žusmu');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6219, 'Lokev');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1318, 'Loški Potok');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2324, 'Lovrenc na Dravskem polju');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2344, 'Lovrenc na Pohorju');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3334, 'Luče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1225, 'Lukovica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9202, 'Mačkovci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2322, 'Majšperk');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2321, 'Makole');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9243, 'Mala Nedelja');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2229, 'Malečnik');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6273, 'Marezige');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2000, 'Maribor ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2001, 'Maribor - poštni predali');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2206, 'Marjeta na Dravskem polju');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2281, 'Markovci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9221, 'Martjanci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6242, 'Materija');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4211, 'Mavčiče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1215, 'Medvode');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1234, 'Mengeš');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8330, 'Metlika');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2392, 'Mežica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2204, 'Miklavž na Dravskem polju');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2275, 'Miklavž pri Ormožu');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5291, 'Miren');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8233, 'Mirna');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8216, 'Mirna Peč');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2382, 'Mislinja');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4281, 'Mojstrana');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8230, 'Mokronog');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1251, 'Moravče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9226, 'Moravske Toplice');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5216, 'Most na Soči');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1221, 'Motnik');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3330, 'Mozirje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9000, 'Murska Sobota ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9001, 'Murska Sobota - poštni predali');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2366, 'Muta');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4202, 'Naklo');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3331, 'Nazarje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1357, 'Notranje Gorice');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3203, 'Nova Cerkev');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5000, 'Nova Gorica ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5001, 'Nova Gorica - poštni predali');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1385, 'Nova vas');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8000, 'Novo mesto');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8001, 'Novo mesto - poštni predali');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6243, 'Obrov');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9233, 'Odranci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2317, 'Oplotnica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2312, 'Orehova vas');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2270, 'Ormož');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1316, 'Ortnek');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1337, 'Osilnica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8222, 'Otočec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2361, 'Ožbalt');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2231, 'Pernica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2211, 'Pesnica pri Mariboru');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9203, 'Petrovci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3301, 'Petrovče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6330, 'Piran/Pirano');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8255, 'Pišece');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6257, 'Pivka');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6232, 'Planina');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3225, 'Planina pri Sevnici');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6276, 'Pobegi');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8312, 'Podbočje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5243, 'Podbrdo');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3254, 'Podčetrtek');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2273, 'Podgorci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6216, 'Podgorje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2381, 'Podgorje pri Slovenj Gradcu');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6244, 'Podgrad');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1414, 'Podkum');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2286, 'Podlehnik');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5272, 'Podnanos');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4244, 'Podnart');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3241, 'Podplat');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3257, 'Podsreda');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2363, 'Podvelka');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2208, 'Pohorje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2257, 'Polenšak');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1355, 'Polhov Gradec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4223, 'Poljane nad Škofjo Loko');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2319, 'Poljčane');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1272, 'Polšnik');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3313, 'Polzela');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3232, 'Ponikva');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6320, 'Portorož/Portorose');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6230, 'Postojna');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2331, 'Pragersko');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3312, 'Prebold');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4205, 'Preddvor');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6255, 'Prem');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1352, 'Preserje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6258, 'Prestranek');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2391, 'Prevalje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3262, 'Prevorje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1276, 'Primskovo ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3253, 'Pristava pri Mestinju');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9207, 'Prosenjakovci/Partosfalva');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5297, 'Prvačina');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2250, 'Ptuj');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2323, 'Ptujska Gora');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9201, 'Puconci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2327, 'Rače');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1433, 'Radeče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9252, 'Radenci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2360, 'Radlje ob Dravi');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1235, 'Radomlje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4240, 'Radovljica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8274, 'Raka');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1381, 'Rakek');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4283, 'Rateče - Planica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2390, 'Ravne na Koroškem');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9246, 'Razkrižje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3332, 'Rečica ob Savinji');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5292, 'Renče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1310, 'Ribnica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2364, 'Ribnica na Pohorju');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3272, 'Rimske Toplice');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1314, 'Rob');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5215, 'Ročinj');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3250, 'Rogaška Slatina');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9262, 'Rogašovci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3252, 'Rogatec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1373, 'Rovte');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2342, 'Ruše');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1282, 'Sava');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6333, 'Sečovlje/Sicciole');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4227, 'Selca');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2352, 'Selnica ob Dravi');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8333, 'Semič');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8281, 'Senovo');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6224, 'Senožeče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8290, 'Sevnica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6210, 'Sežana');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2214, 'Sladki Vrh');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5283, 'Slap ob Idrijci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2380, 'Slovenj Gradec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2310, 'Slovenska Bistrica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3210, 'Slovenske Konjice');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1216, 'Smlednik');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5232, 'Soča');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1317, 'Sodražica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3335, 'Solčava');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5250, 'Solkan');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4229, 'Sorica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4225, 'Sovodenj');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5281, 'Spodnja Idrija');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2241, 'Spodnji Duplek');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9245, 'Spodnji Ivanjci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2277, 'Središče ob Dravi');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4267, 'Srednja vas v Bohinju');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8256, 'Sromlje ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5224, 'Srpenica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1242, 'Stahovica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1332, 'Stara Cerkev');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8342, 'Stari trg ob Kolpi');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1386, 'Stari trg pri Ložu');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2205, 'Starše');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2289, 'Stoperce');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8322, 'Stopiče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3206, 'Stranice');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8351, 'Straža');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1313, 'Struge');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8293, 'Studenec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8331, 'Suhor');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2233, 'Sv. Ana v Slovenskih goricah');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2235, 'Sv. Trojica v Slovenskih goricah');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2353, 'Sveti Duh na Ostrem Vrhu');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9244, 'Sveti Jurij ob Ščavnici');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3264, 'Sveti Štefan');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2258, 'Sveti Tomaž');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9204, 'Šalovci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5261, 'Šempas');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5290, 'Šempeter pri Gorici');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3311, 'Šempeter v Savinjski dolini');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4208, 'Šenčur');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2212, 'Šentilj v Slovenskih goricah');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8297, 'Šentjanž');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2373, 'Šentjanž pri Dravogradu');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8310, 'Šentjernej');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3230, 'Šentjur');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3271, 'Šentrupert');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8232, 'Šentrupert');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1296, 'Šentvid pri Stični');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8275, 'Škocjan');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6281, 'Škofije');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4220, 'Škofja Loka');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3211, 'Škofja vas');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1291, 'Škofljica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6274, 'Šmarje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1293, 'Šmarje - Sap');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3240, 'Šmarje pri Jelšah');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8220, 'Šmarješke Toplice');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2315, 'Šmartno na Pohorju');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3341, 'Šmartno ob Dreti');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3327, 'Šmartno ob Paki');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1275, 'Šmartno pri Litiji');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2383, 'Šmartno pri Slovenj Gradcu');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3201, 'Šmartno v Rožni dolini');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3325, 'Šoštanj');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6222, 'Štanjel');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3220, 'Štore');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3304, 'Tabor');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3221, 'Teharje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9251, 'Tišina');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5220, 'Tolmin');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3326, 'Topolšica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2371, 'Trbonje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1420, 'Trbovlje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8231, 'Trebelno ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8210, 'Trebnje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5252, 'Trnovo pri Gorici');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2254, 'Trnovska vas');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1222, 'Trojane');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1236, 'Trzin');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4290, 'Tržič');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8295, 'Tržišče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1311, 'Turjak');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9224, 'Turnišče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8323, 'Uršna sela');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1252, 'Vače');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3320, 'Velenje ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3322, 'Velenje - poštni predali');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8212, 'Velika Loka');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2274, 'Velika Nedelja');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9225, 'Velika Polana');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1315, 'Velike Lašče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8213, 'Veliki Gaber');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (9241, 'Veržej');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1312, 'Videm - Dobrepolje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2284, 'Videm pri Ptuju');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8344, 'Vinica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5271, 'Vipava');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4212, 'Visoko');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1294, 'Višnja Gora');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3205, 'Vitanje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2255, 'Vitomarci');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1217, 'Vodice');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3212, 'Vojnik');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (5293, 'Volčja Draga');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2232, 'Voličina');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3305, 'Vransko');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (6217, 'Vremski Britof');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1360, 'Vrhnika');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2365, 'Vuhred');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2367, 'Vuzenica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8292, 'Zabukovje ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1410, 'Zagorje ob Savi');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1303, 'Zagradec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2283, 'Zavrč');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8272, 'Zdole ');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4201, 'Zgornja Besnica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2242, 'Zgornja Korena');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2201, 'Zgornja Kungota');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2316, 'Zgornja Ložnica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2314, 'Zgornja Polskava');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2213, 'Zgornja Velka');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4247, 'Zgornje Gorje');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4206, 'Zgornje Jezersko');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2285, 'Zgornji Leskovec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (1432, 'Zidani Most');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3214, 'Zreče');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4209, 'Žabnica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (3310, 'Žalec');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4228, 'Železniki');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (2287, 'Žetale');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4226, 'Žiri');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (4274, 'Žirovnica');
INSERT INTO posta (postna_stevilka, naziv_poste) VALUES (8360, 'Žužemberk');